# # =============================================================================
# # Outputs.
# #
# # These are the values you paste into the Helm install command or the ArgoCD
# # Application. `helm_values_snippet` renders them as ready-to-use YAML so nothing
# # has to be transcribed by hand.
# #
# # No secret is output. The generated password and signing key exist only in
# # Secrets Manager and in Terraform state.
# # =============================================================================

# # -----------------------------------------------------------------------------
# # Cluster
# # -----------------------------------------------------------------------------
# output "cluster_name" {
#   description = "EKS cluster name"
#   value       = module.eks.cluster_name
# }

# output "cluster_endpoint" {
#   description = "Kubernetes API endpoint"
#   value       = module.eks.cluster_endpoint
# }

# output "cluster_oidc_issuer_url" {
#   description = "OIDC issuer URL; the basis of every IRSA trust policy"
#   value       = module.eks.cluster_oidc_issuer_url
# }

# output "configure_kubectl" {
#   description = "Command to point kubectl at this cluster"
#   value       = "aws eks update-kubeconfig --region ${var.aws_region} --name ${module.eks.cluster_name}"
# }

# # -----------------------------------------------------------------------------
# # Networking
# # -----------------------------------------------------------------------------
# output "vpc_id" {
#   description = "VPC id"
#   value       = module.vpc.vpc_id
# }

# output "private_subnet_ids" {
#   description = "Private subnet ids (nodes and pods)"
#   value       = module.vpc.private_subnets
# }

# # -----------------------------------------------------------------------------
# # Registry
# # -----------------------------------------------------------------------------
# output "ecr_registry" {
#   description = "ECR registry host; set as global.imageRegistry"
#   value       = "${data.aws_caller_identity.current.account_id}.dkr.ecr.${var.aws_region}.amazonaws.com"
# }

# output "ecr_repository_urls" {
#   description = "Full repository URLs by component"
#   value       = { for name, repo in aws_ecr_repository.this : name => repo.repository_url }
# }

# # -----------------------------------------------------------------------------
# # IRSA
# # -----------------------------------------------------------------------------
# output "middleware_role_arn" {
#   description = "IRSA role ARN; set as middleware.serviceAccount.roleArn"
#   value       = aws_iam_role.middleware.arn
# }

# output "ai_service_role_arn" {
#   description = "IRSA role ARN; set as aiService.serviceAccount.roleArn"
#   value       = aws_iam_role.ai_service.arn
# }

# output "github_actions_role_arn" {
#   description = "Store as the AWS_DEPLOY_ROLE_ARN GitHub secret"
#   value       = aws_iam_role.github_actions.arn
# }

# # -----------------------------------------------------------------------------
# # Data stores
# # -----------------------------------------------------------------------------
# output "database_endpoint" {
#   description = "RDS endpoint. Informational only: the services read it from Secrets Manager."
#   value       = aws_db_instance.main.address
# }

# output "database_secret_id" {
#   description = "Set as aws.secretsManager.databaseSecretId"
#   value       = aws_secretsmanager_secret.database.name
# }

# output "application_secret_id" {
#   description = "Set as aws.secretsManager.applicationSecretId"
#   value       = aws_secretsmanager_secret.application.name
# }

# output "resume_bucket_name" {
#   description = "Set as middleware.storage.s3.bucket"
#   value       = aws_s3_bucket.resumes.id
# }

# # -----------------------------------------------------------------------------
# # Ready-to-use Helm overrides
# # -----------------------------------------------------------------------------
# output "helm_values_snippet" {
#   description = "Paste into a values file, or save and pass with -f"
#   value       = <<-EOT
#     # Generated by terraform output -raw helm_values_snippet
#     global:
#       imageRegistry: "${data.aws_caller_identity.current.account_id}.dkr.ecr.${var.aws_region}.amazonaws.com"

#     aws:
#       region: "${var.aws_region}"
#       irsa:
#         enabled: true
#       secretsManager:
#         enabled: true
#         databaseSecretId: "${aws_secretsmanager_secret.database.name}"
#         applicationSecretId: "${aws_secretsmanager_secret.application.name}"

#     secrets:
#       create: false

#     postgresql:
#       enabled: false

#     middleware:
#       serviceAccount:
#         roleArn: "${aws_iam_role.middleware.arn}"
#       storage:
#         type: s3
#         s3:
#           bucket: "${aws_s3_bucket.resumes.id}"

#     aiService:
#       serviceAccount:
#         roleArn: "${aws_iam_role.ai_service.arn}"
#   EOT
# }

# output "next_steps" {
#   description = "What to do after apply"
#   value       = <<-EOT

#     1. Point kubectl at the cluster:
#        aws eks update-kubeconfig --region ${var.aws_region} --name ${module.eks.cluster_name}

#     2. Store the deployment role as a GitHub secret named AWS_DEPLOY_ROLE_ARN:
#        ${aws_iam_role.github_actions.arn}

#     3. If using the OpenAI provider, add the key to the application secret
#        (Terraform cannot mint one):
#        aws secretsmanager put-secret-value \
#          --secret-id ${aws_secretsmanager_secret.application.name} \
#          --secret-string "$(aws secretsmanager get-secret-value \
#              --secret-id ${aws_secretsmanager_secret.application.name} \
#              --query SecretString --output text \
#            | jq -c '.openaiApiKey = "sk-REPLACE"')"

#     4. Install the AWS Load Balancer Controller, then deploy:
#        terraform output -raw helm_values_snippet > /tmp/aws-values.yaml
#        helm upgrade --install ai-interview ./helm/ai-interview-platform \
#          -n ${var.kubernetes_namespace} --create-namespace \
#          -f ./helm/ai-interview-platform/values.yaml \
#          -f ./helm/ai-interview-platform/values-prod.yaml \
#          -f /tmp/aws-values.yaml

#     Note: the IRSA trust policies are scoped to namespace "${var.kubernetes_namespace}".
#     Deploying to a different namespace requires updating var.kubernetes_namespace
#     and re-applying, or the pods will fail to assume their roles.
#   EOT
# }
